### ISSUE TITLE
Test different Airflow versions in CI

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#937]
We currently on test Airflow `1.10.12` in CI, let's update jobs `build-integration-airflow` and `test-integration-airflow` to accept an array of Airflow versions (using [matrix](https://circleci.com/blog/circleci-matrix-jobs/) builds) to better identify bugs in older versions. We can start with the following versions:

* 2.0.0
* 1.10.14
* 1.10.12
* 1.10.10
* 1.10.9

See slack discussion [here](https://marquezproject.slack.com/archives/C01E8MQGJP7/p1612523868008000)

**Comment by ashlee3209** [comment]
Hi, I am trying to use the marquez_airflow package on airflow 2.0.1 and saw this error: `ImportError: cannot import name 'LoggingMixin'`. It seems like it imported this module from a wrong place with v2.0.1. Do you have plan to upgrade this library to compatible with the newest airflow version?

**Comment by wslulciuc** [comment]
Hey, @ashlee3209. We've only tested the `marquez-airflow` lib with Airflow `1.10.x`. But, yes, we will be working on support for Airflow `2.0.x`. That said, we are also happy to accept bug fixes for versions we haven't tested yet.

**Comment by julienledem** [comment]
Duplicate of https://github.com/MarquezProject/marquez/issues/1394
